# Generated by Django 3.2 on 2021-05-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, null=True, verbose_name='Tuman')),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Махаля',
                'verbose_name_plural': 'Махали',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, null=True, verbose_name='Bot nomi')),
                ('region', models.CharField(max_length=1024, null=True, verbose_name='Tuman')),
                ('district', models.CharField(max_length=1024, null=True, verbose_name='Mahalla')),
                ('token', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Botlar',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('buttons_uz', models.CharField(blank=True, max_length=700, null=True)),
                ('buttons_ru', models.CharField(blank=True, max_length=700, null=True)),
                ('uz', models.TextField()),
                ('ru', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, null=True)),
                ('request_type', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('problem_type', models.CharField(max_length=255, null=True)),
                ('sub_problem', models.CharField(max_length=255, null=True)),
                ('short_description', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.district')),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabullar',
            },
        ),
    ]
