# Generated by Django 3.1.7 on 2021-04-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('buttons_uz', models.CharField(blank=True, max_length=700, null=True)),
                ('buttons_ru', models.CharField(blank=True, max_length=700, null=True)),
                ('uz', models.TextField()),
                ('ru', models.TextField()),
            ],
        ),
    ]
