# Generated by Django 3.1.7 on 2021-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='token',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
