# Generated by Django 3.1.7 on 2021-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_auto_20210420_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.CharField(max_length=255, null=True, verbose_name='Tuman'),
        ),
    ]
