# Generated by Django 3.1.7 on 2021-04-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_district_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('problem_type', models.CharField(max_length=255, null=True)),
                ('sub_problem', models.CharField(max_length=255, null=True)),
                ('short_description', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.district')),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabullar',
            },
        ),
    ]
