# Generated by Django 3.1.7 on 2021-04-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Bot nomi')),
                ('region', models.CharField(max_length=255, null=True, verbose_name='Tuman')),
                ('token', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Botlar',
            },
        ),
    ]
