# Generated by Django 3.1.7 on 2021-04-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0006_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bot',
            new_name='RegionBot',
        ),
    ]
