# Generated by Django 3.2 on 2021-04-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0013_auto_20210427_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
