# Generated by Django 2.2.20 on 2021-04-27 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Mahalla nomi')),
                ('location', models.CharField(max_length=256, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
            },
        ),
        migrations.CreateModel(
            name='Muammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Muammo nomi')),
            ],
            options={
                'verbose_name': 'Muammo nomi',
                'verbose_name_plural': 'Muammolar',
            },
        ),
        migrations.CreateModel(
            name='SubMuammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, verbose_name='Kategoriya')),
                ('title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='panel.Muammo')),
            ],
            options={
                'verbose_name': 'Kategoriya nomi',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Murojatchi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='Ism Sharifi')),
                ('media', models.FileField(blank=True, null=True, upload_to='muammo_media/', verbose_name='Media')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Manzil')),
                ('description', models.TextField(verbose_name="Qisqacha Ma'lumot")),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Murojat Sanasi')),
                ('updated', models.DateField(auto_now_add=True, verbose_name="O'zgartish Kiritilgan Sana")),
                ('status', models.CharField(choices=[('yopiq', 'yopiq'), ('ochiq', 'ochiq')], max_length=32, verbose_name='Murojatchi Statusi')),
                ('category', models.ForeignKey(blank=True, default='Boshqa', null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.SubMuammo')),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Mahalla')),
                ('muammo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Muammo')),
            ],
            options={
                'verbose_name': 'Murojatchi',
                'verbose_name_plural': 'Murojatchilar',
            },
        ),
    ]
