# Generated by Django 3.2 on 2021-04-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='telegram_id',
            field=models.PositiveBigIntegerField(verbose_name='Telegram ID'),
        ),
    ]
