# Generated by Django 3.2 on 2021-04-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_murojatchi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='murojat_turi',
            field=models.CharField(choices=[('Taklif', 'Taklif'), ('Murojat', 'Murojat'), ('Qabul', 'Qabul')], default=2, max_length=16),
        ),
    ]
