# Generated by Django 3.2 on 2021-04-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_murojatchi_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='muammo',
            name='mahalla',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='panel.mahalla'),
        ),
    ]
