# Generated by Django 3.2 on 2021-04-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_replymessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='murojatchi',
            options={'verbose_name': 'Javob Matni', 'verbose_name_plural': 'Javob Matnlari'},
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='reply_message',
            field=models.TextField(default='Javob berilmagan'),
        ),
        migrations.DeleteModel(
            name='ReplyMessage',
        ),
    ]
