# Generated by Django 3.2 on 2021-04-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_muammo_mahalla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muammo',
            name='mahalla',
        ),
    ]
