# Generated by Django 3.2 on 2021-04-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20210429_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Murojat Sanasi'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='description',
            field=models.TextField(null=True, verbose_name='Murojat Matni'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='fullname',
            field=models.CharField(max_length=256, null=True, verbose_name='Ism Sharifi'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='hudud',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.hudud'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='mahalla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.mahalla'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='murojat_turi',
            field=models.CharField(choices=[('Taklif', 'Taklif'), ('Murojat', 'Murojat'), ('Qabul', 'Qabul')], default=2, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='reply_message',
            field=models.TextField(default='Javob berilmagan', null=True, verbose_name='Javob Matni'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='status',
            field=models.CharField(choices=[("ko'rib chiqilmagan", "ko'rib chiqilmagan"), ("ko'rib chiqilmoqda", "ko'rib chiqilmoqda"), ("ko'rib chiqildi", "ko'rib chiqildi"), ('qabulga chaqirildi', 'qabulga chaqirildi'), ('rad etildi', 'rad etildi')], default="ko'rib chiqilmagan", max_length=32, null=True, verbose_name='Murojatchi Statusi'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='telegram_id',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='updated',
            field=models.DateField(auto_now_add=True, null=True, verbose_name="O'zgartish Kiritilgan Sana"),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='Username'),
        ),
    ]
