# Generated by Django 3.2 on 2021-04-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_murojatchi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hudud',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Hudud'),
        ),
        migrations.AddField(
            model_name='hudud',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Hudud'),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='location_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='location_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Mahalla nomi'),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Mahalla nomi'),
        ),
        migrations.AddField(
            model_name='muammo',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Muammo nomi'),
        ),
        migrations.AddField(
            model_name='muammo',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Muammo nomi'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Murojat Matni'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Murojat Matni'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='fullname_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Ism Sharifi'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='fullname_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Ism Sharifi'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='location_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='location_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='murojat_turi_ru',
            field=models.CharField(choices=[('Taklif', 'Taklif'), ('Murojat', 'Murojat'), ('Qabul', 'Qabul')], default=2, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='murojat_turi_uz',
            field=models.CharField(choices=[('Taklif', 'Taklif'), ('Murojat', 'Murojat'), ('Qabul', 'Qabul')], default=2, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='submuammo',
            name='category_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='submuammo',
            name='category_uz',
            field=models.CharField(max_length=64, null=True, verbose_name='Kategoriya'),
        ),
    ]
