# Generated by Django 3.2 on 2021-04-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20210429_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='murojatchi',
            options={'verbose_name': 'Murojatchi', 'verbose_name_plural': 'Murojatchilar'},
        ),
    ]
