# Generated by Django 3.2 on 2021-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_murojatchi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='description',
            field=models.TextField(verbose_name='Murojat Matni'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='reply_message',
            field=models.TextField(default='Javob berilmagan', verbose_name='Javob Matni'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='status',
            field=models.CharField(choices=[("ko'rib chiqilmagan", "ko'rib chiqilmagan"), ("ko'rib chiqilmoqda", "ko'rib chiqilmoqda"), ("ko'rib chiqildi", "ko'rib chiqildi"), ('rad etildi', 'rad etildi')], max_length=32, verbose_name='Murojatchi Statusi'),
        ),
    ]
