# Generated by Django 3.2 on 2021-04-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20210429_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='hudud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.hudud'),
        ),
    ]
