# Generated by Django 3.2 on 2021-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_murojatchi_hudud'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahalla',
            name='region',
            field=models.CharField(max_length=255, null=True, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='token',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='mahalla',
            name='location',
            field=models.CharField(max_length=256, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='mahalla',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='mahalla',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='Mahalla nomi'),
        ),
    ]
