# Generated by Django 3.2 on 2021-04-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20210429_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='status',
            field=models.CharField(choices=[("ko'rib chiqilmagan", "ko'rib chiqilmagan"), ("ko'rib chiqilmoqda", "ko'rib chiqilmoqda"), ("ko'rib chiqildi", "ko'rib chiqildi"), ('rad etildi', 'rad etildi')], default="ko'rib chiqilmagan", max_length=32, verbose_name='Murojatchi Statusi'),
        ),
    ]
