# Generated by Django 3.2 on 2021-04-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20210429_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murojatchi',
            name='murojat_turi_ru',
        ),
        migrations.RemoveField(
            model_name='murojatchi',
            name='murojat_turi_uz',
        ),
    ]
