# Generated by Django 3.2 on 2021-05-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20210429_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='murojatchi',
            name='day_of_birth',
            field=models.CharField(max_length=256, null=True, verbose_name="Tug'ilgan kun"),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='gender',
            field=models.PositiveBigIntegerField(choices=[(1, 'Erkak'), (2, 'Ayol')], null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='last_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Ism Sharifi'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='middle_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Ism Sharifi'),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='month_of_birth',
            field=models.CharField(max_length=256, null=True, verbose_name="Tug'ilgan oy"),
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='year_of_birth',
            field=models.CharField(max_length=256, null=True, verbose_name="Tug'ilgan yil"),
        ),
    ]
