# Generated by Django 3.2 on 2021-05-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20210429_1753'),
        ('panel', '0008_auto_20210501_1013'),
    ]

    operations = [
    ]
