# Generated by Django 3.2 on 2021-05-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_merge_0007_auto_20210429_1753_0008_auto_20210501_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murojatchi',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='murojatchi',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.submuammo'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Murojat Matni'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Murojat Matni'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Murojat Matni'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='fullname',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ism Sharifi'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='hudud',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='panel.hudud'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.mahalla'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='muammo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.muammo'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='murojat_turi',
            field=models.CharField(choices=[('Taklif', 'Taklif'), ('Murojat', 'Murojat'), ('Qabul', 'Qabul')], default=2, max_length=16),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='reply_message',
            field=models.TextField(default='Javob berilmagan', verbose_name='Javob Matni'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='submuammo',
            name='category',
            field=models.CharField(default='Default', max_length=64, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='submuammo',
            name='category_ru',
            field=models.CharField(default='Default', max_length=64, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='submuammo',
            name='category_uz',
            field=models.CharField(default='Default', max_length=64, null=True, verbose_name='Kategoriya'),
        ),
    ]
