# Generated by Django 3.2 on 2021-05-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20210502_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='murojatchi',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Qabulga Chaqirildi'),
        ),
    ]
