# Generated by Django 3.2 on 2021-05-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_qabul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qabul',
            name='fullname',
        ),
        migrations.AddField(
            model_name='murojatchi',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.qabul'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='day_of_birth',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Tug'ilgan kun"),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='gender',
            field=models.PositiveBigIntegerField(blank=True, choices=[(1, 'Erkak'), (2, 'Ayol')], null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='month_of_birth',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Tug'ilgan oy"),
        ),
        migrations.AlterField(
            model_name='murojatchi',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Tug'ilgan yil"),
        ),
    ]
