# Generated by Django 3.2 on 2021-05-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_murojatchi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Qabulga kiritilmagan'),
        ),
    ]
