# Generated by Django 3.2 on 2021-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_alter_murojatchi_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='title',
            field=models.CharField(blank=True, default='Qabulga kiritilmagan', max_length=256, null=True, verbose_name='Qabul Nomi'),
        ),
    ]
