# Generated by Django 3.2 on 2021-05-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_alter_murojatchi_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qabul',
        ),
    ]
