# Generated by Django 3.2 on 2021-05-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_alter_murojatchi_hudud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murojatchi',
            name='title',
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Qabul Nomi')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('fullname', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.murojatchi')),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabullar',
            },
        ),
    ]
