# Generated by Django 3.2 on 2021-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_auto_20210503_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
