# Generated by Django 3.2 on 2021-05-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_reception_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='fullname',
            new_name='telegram_id',
        ),
    ]
