# Generated by Django 3.2 on 2021-05-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_reception_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='fullname',
        ),
        migrations.CreateModel(
            name='ReceptionUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.reception')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.murojatchi')),
            ],
            options={
                'verbose_name': 'Reception User',
                'verbose_name_plural': 'Reception Users',
            },
        ),
    ]
