# Generated by Django 3.2 on 2021-05-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_rename_fullname_reception_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahalla',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Mahalla nomi_ru'),
        ),
        migrations.AlterField(
            model_name='mahalla',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Mahalla nomi_uz'),
        ),
    ]
