# Generated by Django 3.2 on 2021-05-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_auto_20210503_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionusers',
            old_name='reception',
            new_name='title',
        ),
    ]
