# Generated by Django 3.2 on 2021-05-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_rename_reception_receptionusers_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.murojatchi'),
        ),
        migrations.DeleteModel(
            name='ReceptionUsers',
        ),
    ]
