# Generated by Django 3.2 on 2021-05-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_auto_20210503_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahalla',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mahalla',
            name='name_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
