# Generated by Django 3.2 on 2021-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_auto_20210503_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='users',
        ),
        migrations.AddField(
            model_name='reception',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='panel.Murojatchi'),
        ),
    ]
