# Generated by Django 3.2 on 2021-05-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_alter_murojatchi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
