# Generated by Django 3.2 on 2021-05-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_reception_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.IntegerField(choices=[(1, "Ko'rib Chiqildi"), (2, "Ko'rib Chiqilmoqda"), (3, "Ko'rib Chiqilmagan")], default=3),
        ),
    ]
