# Generated by Django 3.2 on 2021-05-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_alter_reception_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='murojat_turi',
            field=models.CharField(blank=True, choices=[('Murojat', 'Murojat'), ('Qabul', 'Qabul')], max_length=16, null=True),
        ),
    ]
