# Generated by Django 3.2 on 2021-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_auto_20210504_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='murojat_turi',
            field=models.CharField(blank=True, choices=[('appeal', 'Murojat'), ('admission', 'Qabul')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='users',
            field=models.ManyToManyField(to='panel.Murojatchi'),
        ),
    ]
