# Generated by Django 3.2 on 2021-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_auto_20210504_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='panel.Murojatchi'),
        ),
    ]
