# Generated by Django 3.2 on 2021-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0032_alter_reception_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, "Ko'rib Chiqildi"), (2, "Ko'rib Chiqilmoqda"), (3, "Ko'rib Chiqilmagan")], default=3, null=True),
        ),
    ]
