# Generated by Django 3.2 on 2021-05-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_alter_reception_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murojatchi',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='murojatchi',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='murojatchi',
            name='description_uz',
        ),
    ]
