# Generated by Django 3.2 on 2021-05-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0035_alter_reception_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, max_length=256, null=True, verbose_name="Tug'ilgan yil"),
        ),
    ]
