# Generated by Django 3.2 on 2021-05-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0038_auto_20210504_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murojatchi',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Tug'ilgan yil"),
        ),
    ]
