GET_LANG, STATEMENT_TYPE, MAIN, GET_FIRST_NAME, GET_LAST_NAME, GET_MIDDLE_NAME, GET_DISTRICT, GET_PROBLEM_TYPE, \
    GET_COMMUNAL_PROBLEM, GET_LAND_ISSUES_PROBLEM, GET_SHORT_DESCRIPTION, GET_SOCIAL_SECURITY_PROBLEM, \
    GET_PHONE_NUMBER, GET_FILE, GET_LOCATION, MAIN_MENU = range(16)
