GET_LANG, STATEMENT_TYPE, MAIN, GET_FIRST_NAME, GET_LAST_NAME, GET_MIDDLE_NAME, GET_DISTRICT, GET_PROBLEM_TYPE, \
    GET_COMMUNAL_PROBLEM, GET_LAND_ISSUES_PROBLEM, GET_SHORT_DESCRIPTION, GET_SOCIAL_SECURITY_PROBLEM = range(12)
